USE cs308_store;

CREATE TABLE IF NOT EXISTS addresses (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  label VARCHAR(50) NOT NULL,
  recipient VARCHAR(512) NOT NULL,
  line1 VARCHAR(1024) NOT NULL,
  city VARCHAR(512) NOT NULL,
  postal VARCHAR(256) DEFAULT NULL,
  country VARCHAR(100) NOT NULL DEFAULT 'Türkiye',
  is_default TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

ALTER TABLE orders ADD COLUMN address_id INT;

ALTER TABLE orders ADD CONSTRAINT fk_order_address FOREIGN KEY (address_id) REFERENCES addresses(id) ON DELETE SET NULL;